### ISSUE TITLE
Portuguese BERT

### ISSUE THREAD

**Issue by manueltonneau** [pvcastro/treinamento_lda#1]
Hi Pedro,

Cool stuff on LDA for Portuguese. I am currently pre-training BERT on a Portuguese corpus and am looking for benchmarks to evaluate my model. I saw that you are also pre-training ALBERT for Portuguese: do you have any resources you could share? Sorry for reaching out here, I looked for your contact but wasn't able to find it. We can also have a call to discuss a potential collaboration :)

**Comment by pvcastro** [comment]
Hi @mananeau! Send me your WhatsApp at pvcastro@gmail.com. Let's chat there 👍🏻

**Comment by manueltonneau** [comment]
Thanks, just sent you an email :)
